name: Validate Terraform Docs

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  docs:
    name: Validate Terraform Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: v1.14.3

      - name: Check Terraform Docs
        uses: terraform-docs/gh-actions@v1.4.1
        with:
          working-dir: .
          fail-on-diff: "true"